
//2.1
#include <stdio.h>

main()
{
    int z;
    int w;
    int x = 1;
    int y = 2;
    z = y + x;
    w = y - x;
}


/*
//2.2
#define PI 3.14159
#include <stdio.h>

main()
{
    int a = 5;
    float b = 23.5;
    int c = 31000;
    printf("%d метрів тканини коштувало %f гривень.\n", a, b);
    printf("значення числа pi рівне %f.\n", PI);
    printf(" IBM сумісні комп'ютери набули широкого розповсюдження.\n");
    printf("%c%d\n", '$', c);
}
*/

/*
//2.3
#include <stdio.h>

main()
{
    printf("/%d/\n", 557);
    printf("/%10d/\n", 557);
    printf("/%-10d/\n", 557);
}
*/

/*
//2.4
#include <stdio.h>

main()
{
    printf("/%d/\n", 21949);
    printf("/%d/\n", -1611);
    printf("/%d/\n", -8380);
    printf("/%d/\n", 21943);
}
*/

/*
//2.5

main()
{
    printf("/%f/\n", 6543.21);
    printf("/%e/\n", 6543.21);
    printf("/%4.2f/\n", 6543.21);
    printf("/%3.1f/\n", 6543.21);
    printf("/ .3f/\n", 6543.21);
    printf("/ .3e/\n", 6543.21);
}
*/

/*
//2.6
#define riadok "Чудова погода" 

main()
{
    printf("/%2s/\n" riadok);
    printf("/%15.s/\n" riadok);
}
*/

/*
//2.7
main()
{
    printf("%d\n", 557);
    printf("%o\n", 557);
    printf("%x\n", 557);
    printf("%d\n", -557);
}
*/
/*
//2.8
#include<stdio.h>
main()
{
    int vik;
    char name [30];
    printf("Vash vik?\n");
    scanf("%d", &vik);
    printf("Vvedit vashe imya?\n");
    scanf( log_5(pi) name);
    printf("Pryvit %s jakomy(iy) %d rokiv", name, vik);
}
*/
/*
//2.9
#include<stdio.h>
#include<conio.h>
#define STOP '*'
main()
{
    char ch;
    ch = getchar();
ml:if (ch I =STOP)
{
    putchar(ch);
    ch = getchar(); goto ml;
}
}
*/