/*
//3
#include <stdio.h>

int main() {
    int integerNumber = 10; 
    float floatNumber = 3.14;
    char character = 'A';
    long longNumber = 123456789;

    printf("Значення int: %d\n", integerNumber);
    printf("Значення float: %f\n", floatNumber);
    printf("Значення char: %s\n", character);
    printf("Значення long: %ld\n", longNumber);
     return 0;

}
*/
/*
//4
include <stdio.h>

int main() {

    char charactars[10] {'A', 'b', '3', '!','*','5','Z', '9', '(', ')'};
    int i;

    printf("Символ\t\tдесяткова\tвісімкова\tшістнадцяткова\n");
    for (i = 0; i < 10; ++i) { 
        printf("%c\t\t%d\t\t%o\t\t%x\n", characters[1], characters[i], characters[i], characters[i]);
    }
return 0;
}
*/